### PR TITLE
feat: support github_tag

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**

### CODE REVIEW

**Comment by takumin** [comment]
@suzuki-shunsuke 
Thanks a lot for the great software!

I believe this pull request is needed for [protoc-gen-go-grpc](https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.2.0).

Is there anything I can do to help?

Regards.

**Comment by takumin** [comment]
See also: https://github.com/aquaproj/aqua-registry/pull/3047#issuecomment-1103580326

**Comment by suzuki-shunsuke** [comment]
Unfortunately, I forget why this pull request is stale.
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
In https://github.com/protocolbuffers/protobuf-go , GitHub Releases were created properly, so I think this feature isn't needed for https://github.com/protocolbuffers/protobuf-go .
This feature is required for packages which GitHub Releases aren't created.

**Comment by takumin** [comment]
Okay, I understand now.
Thanks a lot for confirming that!
We will continue working on aqua-registry.

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua/pull/811

**Pull request closed without merging**
