### PR TITLE
feat: support uninstalling packages

### LINKED ISSUE #538: Support "aqua remove" or "aqua clean" - removing package
```diff
---
  # aqua - Declarative CLI Version Manager
  # https://aquaproj.github.io/
  registries:
  - type: standard
    ref: v0.13.1 # renovate: depName=aquaproj/aqua-registry

  packages:
  - name: cli/cli@v2.2.0
- - name: junegunn/fzf@0.28.0
```

```console
$ aqua clean  # remove package automatically
```

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Close #538

## Features

Add a subcommand `rm` to uninstall packages

### Usage

```console
$ aqua rm --all [-a] # Uninstall all packages
```

```console
$ aqua rm [<registry name>,]<package name> [...] # Uninstall packages
```

### Example

```console
$ aqua rm -a
```

```console
$ aqua rm cli/cli direnv/direnv
```

### ⚠️ Limitation

The following package types can't be removed without `--all` option.

- `http`
- `go_install`

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
TODO

- [ ] `-c` specify command names
- [ ] `-i` select packages interactively with fuzzy finder

**Comment by 4513ECHO** [comment]
I think it is  better to use `remove` for the command name and use `rm` as an alias.

**Comment by suzuki-shunsuke** [comment]
Thank you for your comment.
It makes sense. Fixed. 389fb9531d9622671117cf709a0bf3b7b1024c13

**Comment by suzuki-shunsuke** [comment]
> TODO
> 
> * [ ]  `-c` specify command names
> * [ ]  `-i` select packages interactively with fuzzy finder

These features are useful, but I don't implement them for now.
We'll implement them when they are really necessary.
I'd like to release this command and check the feedback before implementing them.

**Comment by ryoppippi** [comment]
Thanks!!!

**Pull request merged**
